/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyEntry {
  'weight' : [] | [Measurement],
  'workouts' : Array<Workout>,
  'date' : Time,
  'hips' : [] | [Measurement],
  'chest' : [] | [Measurement],
  'image' : [] | [ExternalBlob],
  'waist' : [] | [Measurement],
}
export type ExternalBlob = Uint8Array;
export type Gender = { 'other' : string } |
  { 'female' : null } |
  { 'male' : null };
export interface Measurement {
  'value' : number,
  'date' : Time,
  'unit' : { 'cm' : null } |
    { 'inches' : null },
}
export type Time = bigint;
export interface Units {
  'weight' : { 'kg' : null } |
    { 'lbs' : null },
  'measurements' : { 'cm' : null } |
    { 'inches' : null },
}
export interface UserProfile {
  'age' : bigint,
  'name' : string,
  'gender' : Gender,
  'units' : Units,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Workout {
  'duration' : bigint,
  'date' : Time,
  'muscleGroups' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateEntry' : ActorMethod<[DailyEntry], undefined>,
  'deleteEntry' : ActorMethod<[Time], undefined>,
  'getAllEntries' : ActorMethod<[], Array<DailyEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComparisonImages' : ActorMethod<
    [],
    {
      'day1' : [] | [DailyEntry],
      'day30' : [] | [DailyEntry],
      'day90' : [] | [DailyEntry],
    }
  >,
  'getEntryByDate' : ActorMethod<[Time], [] | [DailyEntry]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeightEntries' : ActorMethod<[], Array<Measurement>>,
  'getWorkoutEntries' : ActorMethod<[], Array<Workout>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];