/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Measurement = IDL.Record({
  'value' : IDL.Float64,
  'date' : Time,
  'unit' : IDL.Variant({ 'cm' : IDL.Null, 'inches' : IDL.Null }),
});
export const Workout = IDL.Record({
  'duration' : IDL.Nat,
  'date' : Time,
  'muscleGroups' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DailyEntry = IDL.Record({
  'weight' : IDL.Opt(Measurement),
  'bodyFatPercent' : IDL.Opt(IDL.Float64),
  'workouts' : IDL.Vec(Workout),
  'date' : Time,
  'hips' : IDL.Opt(Measurement),
  'chest' : IDL.Opt(Measurement),
  'image' : IDL.Opt(ExternalBlob),
  'waist' : IDL.Opt(Measurement),
});
export const Gender = IDL.Variant({
  'other' : IDL.Text,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const Units = IDL.Record({
  'weight' : IDL.Variant({ 'kg' : IDL.Null, 'lbs' : IDL.Null }),
  'measurements' : IDL.Variant({ 'cm' : IDL.Null, 'inches' : IDL.Null }),
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'gender' : Gender,
  'units' : Units,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateEntry' : IDL.Func([DailyEntry], [], []),
  'deleteEntry' : IDL.Func([Time], [], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(DailyEntry)], ['query']),
  'getBodyFatEntries' : IDL.Func(
      [],
      [IDL.Vec(IDL.Record({ 'bodyFatPercent' : IDL.Float64, 'date' : Time }))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChestEntries' : IDL.Func([], [IDL.Vec(Measurement)], ['query']),
  'getComparisonEntries' : IDL.Func(
      [Time, Time, Time],
      [
        IDL.Record({
          'entry1' : IDL.Opt(DailyEntry),
          'entry2' : IDL.Opt(DailyEntry),
          'entry3' : IDL.Opt(DailyEntry),
        }),
      ],
      ['query'],
    ),
  'getEntryByDate' : IDL.Func([Time], [IDL.Opt(DailyEntry)], ['query']),
  'getHipsEntries' : IDL.Func([], [IDL.Vec(Measurement)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWaistEntries' : IDL.Func([], [IDL.Vec(Measurement)], ['query']),
  'getWeightEntries' : IDL.Func([], [IDL.Vec(Measurement)], ['query']),
  'getWorkoutDurationTimeSeries' : IDL.Func(
      [],
      [IDL.Vec(IDL.Record({ 'date' : Time, 'totalDuration' : IDL.Nat }))],
      ['query'],
    ),
  'getWorkoutEntries' : IDL.Func([], [IDL.Vec(Workout)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Measurement = IDL.Record({
    'value' : IDL.Float64,
    'date' : Time,
    'unit' : IDL.Variant({ 'cm' : IDL.Null, 'inches' : IDL.Null }),
  });
  const Workout = IDL.Record({
    'duration' : IDL.Nat,
    'date' : Time,
    'muscleGroups' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DailyEntry = IDL.Record({
    'weight' : IDL.Opt(Measurement),
    'bodyFatPercent' : IDL.Opt(IDL.Float64),
    'workouts' : IDL.Vec(Workout),
    'date' : Time,
    'hips' : IDL.Opt(Measurement),
    'chest' : IDL.Opt(Measurement),
    'image' : IDL.Opt(ExternalBlob),
    'waist' : IDL.Opt(Measurement),
  });
  const Gender = IDL.Variant({
    'other' : IDL.Text,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const Units = IDL.Record({
    'weight' : IDL.Variant({ 'kg' : IDL.Null, 'lbs' : IDL.Null }),
    'measurements' : IDL.Variant({ 'cm' : IDL.Null, 'inches' : IDL.Null }),
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'gender' : Gender,
    'units' : Units,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateEntry' : IDL.Func([DailyEntry], [], []),
    'deleteEntry' : IDL.Func([Time], [], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(DailyEntry)], ['query']),
    'getBodyFatEntries' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({ 'bodyFatPercent' : IDL.Float64, 'date' : Time })
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChestEntries' : IDL.Func([], [IDL.Vec(Measurement)], ['query']),
    'getComparisonEntries' : IDL.Func(
        [Time, Time, Time],
        [
          IDL.Record({
            'entry1' : IDL.Opt(DailyEntry),
            'entry2' : IDL.Opt(DailyEntry),
            'entry3' : IDL.Opt(DailyEntry),
          }),
        ],
        ['query'],
      ),
    'getEntryByDate' : IDL.Func([Time], [IDL.Opt(DailyEntry)], ['query']),
    'getHipsEntries' : IDL.Func([], [IDL.Vec(Measurement)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWaistEntries' : IDL.Func([], [IDL.Vec(Measurement)], ['query']),
    'getWeightEntries' : IDL.Func([], [IDL.Vec(Measurement)], ['query']),
    'getWorkoutDurationTimeSeries' : IDL.Func(
        [],
        [IDL.Vec(IDL.Record({ 'date' : Time, 'totalDuration' : IDL.Nat }))],
        ['query'],
      ),
    'getWorkoutEntries' : IDL.Func([], [IDL.Vec(Workout)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };